spring.application.name=pws

# Database Connection (Using MySQL Driver for MariaDB)
# Note: We use 'jdbc:mysql' because we are using the MySQL driver
spring.datasource.url=jdbc:mysql://localhost:3306/pws
spring.datasource.username=root
spring.datasource.password=madmax
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Even though we use the MySQL driver, we tell Hibernate the underlying DB is MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
